[package]
name = "portier-mcp"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
libportier = { path = "../libportier" }
rmcp = { version = "1.8.0", features = ["server", "macros", "transport-io"] }
tokio = { version = "1.52.3", features = ["full"] }

[lib]
name = "portier_mcp"
crate-type = ["lib"]
